apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: zovarc
  labels:
    app: zovarc
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: zovarc
    component: redis
