apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: zovark
  labels:
    app: zovark
    component: pgbouncer
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: pgbouncer
  selector:
    app: zovark
    component: pgbouncer
