#!/usr/bin/env python3
"""
IMMUTABLE EVALUATION HARNESS — Do NOT modify this file.
Tests a candidate template against alerts and scores fitness.
Loads test data from test_alerts.json (generated by setup_test_alerts.py).
"""

import json
import sys
import os
import ast
import time
import subprocess
import tempfile
from datetime import datetime

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, PROJECT_ROOT)
sys.path.insert(0, os.path.dirname(__file__))

from candidate import TEMPLATE_CODE, TEMPLATE_METADATA

# --- Load test alerts ---
TEST_ALERTS_PATH = os.path.join(os.path.dirname(__file__), "test_alerts.json")
if os.path.exists(TEST_ALERTS_PATH):
    with open(TEST_ALERTS_PATH) as f:
        ALL_TEST_ALERTS = json.load(f)
else:
    print("ERROR: test_alerts.json not found. Run setup_test_alerts.py first.")
    sys.exit(1)

ALLOWED_MODULES = {
    "json", "re", "datetime", "collections", "math", "hashlib",
    "ipaddress", "base64", "urllib", "csv", "statistics",
    "string", "copy", "itertools", "functools", "typing",
}

BLOCKED_BUILTINS = {"open", "eval", "exec", "compile", "__import__", "breakpoint"}


def validate_ast(code: str) -> tuple:
    """AST prefilter. Returns (is_valid, error)."""
    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        return False, f"Syntax error: {e}"

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.split(".")[0]
                if root not in ALLOWED_MODULES:
                    return False, f"Forbidden import: {alias.name}"
        elif isinstance(node, ast.ImportFrom) and node.module:
            root = node.module.split(".")[0]
            if root not in ALLOWED_MODULES:
                return False, f"Forbidden import: {node.module}"
        elif isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            if node.func.id in BLOCKED_BUILTINS:
                return False, f"Forbidden builtin: {node.func.id}"

    return True, None


def run_template(code: str, siem_event: dict, timeout: float = 5.0) -> dict:
    """Execute template with SIEM event. Returns parsed JSON or error dict."""
    rendered = code.replace("{{siem_event_json}}", json.dumps(siem_event))

    with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
        f.write(rendered)
        f.flush()
        try:
            result = subprocess.run(
                [sys.executable, f.name],
                capture_output=True, text=True, timeout=timeout,
            )
            if result.returncode != 0:
                return {"error": f"Exit {result.returncode}: {result.stderr[:200]}"}
            try:
                return json.loads(result.stdout)
            except json.JSONDecodeError:
                return {"error": f"Invalid JSON: {result.stdout[:200]}"}
        except subprocess.TimeoutExpired:
            return {"error": "Timeout (>5s)"}
        finally:
            os.unlink(f.name)


def evaluate() -> dict:
    """Full evaluation of the current candidate template."""
    task_type = TEMPLATE_METADATA.get("task_type", "unknown")

    # Step 1: AST validation
    is_valid, ast_err = validate_ast(TEMPLATE_CODE)
    if not is_valid:
        return {"fitness": 0.0, "error": f"AST: {ast_err}", "task_type": task_type}

    # Step 2: Get test alerts
    alerts = ALL_TEST_ALERTS.get(task_type, {})
    attack_alerts = alerts.get("attacks", [])
    benign_alerts = alerts.get("benign", [])

    if not attack_alerts:
        return {"fitness": 0.0, "error": f"No test alerts for '{task_type}'", "task_type": task_type}

    # Step 3: Split into training (75%) and holdout (25%)
    split_a = max(1, int(len(attack_alerts) * 0.75))
    split_b = max(1, int(len(benign_alerts) * 0.75))
    train_attacks = attack_alerts[:split_a]
    train_benign = benign_alerts[:split_b]
    holdout_attacks = attack_alerts[split_a:]
    holdout_benign = benign_alerts[split_b:]

    # Step 4: Evaluate on training set
    correct = 0
    total = 0
    false_negatives = 0
    total_ms = 0.0
    total_ioc_expected = 0
    total_ioc_found = 0
    details = []

    for alert in train_attacks:
        total += 1
        start = time.time()
        output = run_template(TEMPLATE_CODE, alert["siem_event"])
        elapsed = (time.time() - start) * 1000
        total_ms += elapsed

        if "error" in output:
            false_negatives += 1
            details.append(f"ATTACK ERROR: {output['error'][:80]}")
            continue

        risk = output.get("risk_score", 0)
        verdict = output.get("verdict", "")
        min_risk = alert.get("expected_min_risk", 70)

        if risk >= min_risk and verdict in ("true_positive", "suspicious"):
            correct += 1
        else:
            false_negatives += 1
            details.append(f"FN: risk={risk} verdict={verdict} (need >={min_risk})")

        expected = set(alert.get("expected_iocs", []))
        found = set()
        for ioc in output.get("iocs", []):
            v = ioc.get("value", "") if isinstance(ioc, dict) else str(ioc)
            found.add(v)
        total_ioc_expected += len(expected)
        total_ioc_found += len(expected & found)

    for alert in train_benign:
        total += 1
        start = time.time()
        output = run_template(TEMPLATE_CODE, alert["siem_event"])
        elapsed = (time.time() - start) * 1000
        total_ms += elapsed

        if "error" in output:
            details.append(f"BENIGN ERROR: {output['error'][:80]}")
            continue

        risk = output.get("risk_score", 0)
        max_risk = alert.get("expected_max_risk", 35)
        if risk <= max_risk:
            correct += 1
        else:
            details.append(f"FP: risk={risk} (need <={max_risk})")

    # Step 5: Hard constraint check
    if false_negatives > 0:
        return {
            "fitness": 0.0, "error": f"{false_negatives} false negatives",
            "details": details, "task_type": task_type,
        }

    accuracy = correct / total if total > 0 else 0
    avg_ms = total_ms / total if total > 0 else 9999

    if accuracy < 0.95:
        return {
            "fitness": round(accuracy * 0.1, 4),
            "error": f"Accuracy {accuracy:.2%} < 95%",
            "details": details, "task_type": task_type,
        }
    if avg_ms > 2000:
        return {
            "fitness": 0.0, "error": f"Too slow: {avg_ms:.0f}ms",
            "task_type": task_type,
        }

    speed_score = max(0, 500 - avg_ms) / 500
    ioc_recall = total_ioc_found / total_ioc_expected if total_ioc_expected > 0 else 0
    fitness = 0.6 * accuracy + 0.2 * speed_score + 0.2 * ioc_recall

    # Step 6: Holdout validation (only if fitness >= 0.90)
    holdout_pass = True
    if fitness >= 0.90 and (holdout_attacks or holdout_benign):
        for alert in holdout_attacks:
            output = run_template(TEMPLATE_CODE, alert["siem_event"])
            if "error" in output:
                holdout_pass = False
                details.append(f"HOLDOUT FAIL (attack): {output['error'][:80]}")
                break
            risk = output.get("risk_score", 0)
            verdict = output.get("verdict", "")
            if risk < alert.get("expected_min_risk", 70) or verdict not in ("true_positive", "suspicious"):
                holdout_pass = False
                details.append(f"HOLDOUT FAIL: risk={risk} verdict={verdict}")
                break

        for alert in holdout_benign:
            output = run_template(TEMPLATE_CODE, alert["siem_event"])
            if "error" not in output:
                risk = output.get("risk_score", 0)
                if risk > alert.get("expected_max_risk", 35):
                    holdout_pass = False
                    details.append(f"HOLDOUT FP: risk={risk}")
                    break

        if not holdout_pass:
            fitness = min(fitness, 0.89)
            details.append("Holdout validation FAILED — template may be overfit")

    result = {
        "fitness": round(fitness, 4),
        "accuracy": round(accuracy, 4),
        "avg_ms": round(avg_ms, 1),
        "ioc_recall": round(ioc_recall, 4),
        "correct": correct,
        "total": total,
        "false_negatives": false_negatives,
        "holdout_pass": holdout_pass,
        "details": details,
        "task_type": task_type,
        "timestamp": datetime.utcnow().isoformat(),
    }

    # Log
    results_path = os.path.join(os.path.dirname(__file__), "results.jsonl")
    with open(results_path, "a") as f:
        f.write(json.dumps(result) + "\n")

    # Save approved templates
    if fitness >= 0.90 and holdout_pass:
        approved_dir = os.path.join(os.path.dirname(__file__), "approved")
        os.makedirs(approved_dir, exist_ok=True)
        path = os.path.join(approved_dir, f"{task_type}_template.json")
        with open(path, "w") as f:
            json.dump({
                "template_code": TEMPLATE_CODE,
                "metadata": TEMPLATE_METADATA,
                "fitness": result["fitness"],
                "accuracy": result["accuracy"],
                "avg_ms": result["avg_ms"],
                "ioc_recall": result["ioc_recall"],
                "holdout_pass": True,
                "timestamp": result["timestamp"],
            }, f, indent=2)
        print(f"*** APPROVED: {path} ***")

    # Summary for agent
    print(f"Fitness: {result['fitness']:.4f}")
    print(f"Accuracy: {result['accuracy']:.2%}")
    print(f"Speed: {result['avg_ms']:.0f}ms avg")
    print(f"IOC recall: {result['ioc_recall']:.2%}")
    print(f"Holdout: {'PASS' if holdout_pass else 'FAIL'}")
    for d in details[:5]:
        print(f"  {d}")

    return result


if __name__ == "__main__":
    evaluate()
