#!/usr/bin/env python3
"""
HYDRA DPO Training Script

Trains the 1.5B model using Direct Preference Optimization on the
generated dataset. Fits on RTX 3050 (4GB VRAM).

Prerequisites:
  pip install -r dpo/requirements.txt
  # Dataset: hydra_dpo_dataset.jsonl (generated by dpo/dpo_forge.py)

Usage:
  python scripts/dpo_train.py
  python scripts/dpo_train.py --dataset custom_dataset.jsonl
  python scripts/dpo_train.py --epochs 2
"""
import argparse
import sys


def main():
    parser = argparse.ArgumentParser(description="HYDRA DPO Training")
    parser.add_argument("--dataset", default="hydra_dpo_dataset.jsonl")
    parser.add_argument("--epochs", type=int, default=1)
    parser.add_argument("--output-dir", default="hydra_dpo_outputs")
    parser.add_argument("--model-name", default="hydra_aligned_1.5b")
    args = parser.parse_args()

    try:
        from unsloth import FastLanguageModel, PatchDPOTrainer
        from trl import DPOTrainer, DPOConfig
        from datasets import load_dataset
    except ImportError as e:
        print(f"Missing dependency: {e}")
        print("Install with: pip install -r dpo/requirements.txt")
        sys.exit(1)

    PatchDPOTrainer()

    max_seq_length = 2048  # Bumped from 1024 — adds 24MB KV cache, fits RTX 3050

    print("Loading model...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name="unsloth/Qwen2.5-1.5B-Instruct",
        max_seq_length=max_seq_length,
        dtype=None,
        load_in_4bit=True,
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r=16,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                         "gate_proj", "up_proj", "down_proj"],
        lora_alpha=16,
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )

    print(f"Loading dataset from {args.dataset}...")
    dataset = load_dataset("json", data_files=args.dataset, split="train")

    # Validate token budgets before training
    print(f"Dataset size: {len(dataset)} pairs")
    over_budget = 0
    for i, row in enumerate(dataset):
        prompt_len = len(tokenizer.encode(row["prompt"]))
        chosen_len = len(tokenizer.encode(row["chosen"]))
        rejected_len = len(tokenizer.encode(row["rejected"]))
        total = prompt_len + max(chosen_len, rejected_len)
        if prompt_len > 600:
            print(f"WARNING: Row {i} prompt={prompt_len} tokens (over 600)")
            over_budget += 1
        if total > max_seq_length:
            print(f"WARNING: Row {i} total={total} tokens (over {max_seq_length})")
            over_budget += 1
    if over_budget > 0:
        print(f"WARNING: {over_budget} rows exceed token budget")
    else:
        print("All rows within token budget")

    print("Starting DPO training...")
    dpo_trainer = DPOTrainer(
        model=model,
        ref_model=None,  # Unsloth handles this internally
        tokenizer=tokenizer,
        beta=0.1,
        train_dataset=dataset,
        max_length=max_seq_length,
        max_prompt_length=600,  # Hard ceiling — matches log compressor
        args=DPOConfig(
            per_device_train_batch_size=1,
            gradient_accumulation_steps=8,
            warmup_ratio=0.1,
            num_train_epochs=args.epochs,
            learning_rate=5e-6,
            fp16=not FastLanguageModel.is_bfloat16_supported(),
            bf16=FastLanguageModel.is_bfloat16_supported(),
            logging_steps=10,
            optim="adamw_8bit",
            output_dir=args.output_dir,
        ),
    )

    dpo_trainer.train()

    print(f"Saving model to {args.model_name}/...")
    model.save_pretrained_gguf(
        args.model_name,
        tokenizer,
        quantization_method="q4_k_m"
    )

    print(f"Model saved: {args.model_name}/")
    print(f"Run: python scripts/accuracy_benchmark.py --model {args.model_name}")


if __name__ == "__main__":
    main()
