import type { WorkflowStep } from '../types';

const BASE_TIME = '2026-03-09T14:32:00.000Z';

function offsetTime(ms: number): string {
  return new Date(new Date(BASE_TIME).getTime() + ms).toISOString();
}

export const C2_BEACON_STEPS: WorkflowStep[] = [
  {
    id: 'step-001',
    name: 'parse_alert',
    status: 'completed',
    started_at: offsetTime(0),
    completed_at: offsetTime(500),
    duration_ms: 500,
    input: {
      alert_source: 'suricata',
      rule_id: 'ET TROJAN DNS Beacon',
      raw_alert: 'DNS beaconing detected to updateservice-cdn.net from 10.0.5.42 (interval ~30s)',
    },
    output: {
      iocs_extracted: 3,
      domain: 'updateservice-cdn.net',
      src_ip: '10.0.5.42',
      alert_type: 'C2 Beacon Communication',
      beacon_interval_seconds: 30,
    },
    retry_count: 0,
    execution_context: 'local',
  },
  {
    id: 'step-002',
    name: 'generate_python',
    status: 'completed',
    started_at: offsetTime(500),
    completed_at: offsetTime(4700),
    duration_ms: 4200,
    model_name: 'zovarc-standard',
    input: {
      task: 'Investigate DNS beaconing to updateservice-cdn.net from internal host 10.0.5.42',
      iocs: ['updateservice-cdn.net', '10.0.5.42'],
      investigation_type: 'c2_beacon',
    },
    output: {
      code_lines: 87,
      modules_used: ['dns.resolver', 'requests', 'ipwhois', 'json'],
      checks: [
        'virustotal_domain_lookup',
        'whois_registration_age',
        'reverse_dns',
        'ip_geolocation',
        'tor_exit_node_check',
        'beacon_interval_analysis',
      ],
    },
    retry_count: 0,
    execution_context: 'llm',
  },
  {
    id: 'step-003',
    name: 'execute_sandbox',
    status: 'completed',
    started_at: offsetTime(4700),
    completed_at: offsetTime(5800),
    duration_ms: 1100,
    input: {
      sandbox_type: 'docker',
      network_mode: 'none',
      timeout_seconds: 30,
      seccomp_profile: 'zovarc-sandbox',
    },
    output: {
      exit_code: 0,
      virustotal_detections: '14/72 vendors flagged updateservice-cdn.net',
      whois_registration: '2026-03-06 (3 days ago)',
      resolved_ip: '185.220.101.34',
      ip_context: 'Known Tor exit node (DE)',
      beacon_interval: '30.2s average (±0.8s jitter)',
      dns_queries_last_hour: 119,
      process_name: 'svchost-update.exe',
      process_user: 'CORP\\jthompson',
    },
    retry_count: 0,
    execution_context: 'local',
  },
  {
    id: 'step-004',
    name: 'extract_entities',
    status: 'completed',
    started_at: offsetTime(5800),
    completed_at: offsetTime(6100),
    duration_ms: 300,
    input: {
      extraction_source: 'sandbox_output',
      entity_types: ['domain', 'ip', 'process', 'user', 'file'],
    },
    output: {
      entity_count: 5,
      entities: [
        { type: 'domain', value: 'updateservice-cdn.net', malicious: true },
        { type: 'ip', value: '185.220.101.34', context: 'Tor exit node' },
        { type: 'ip', value: '10.0.5.42', context: 'Internal source host' },
        { type: 'process', value: 'svchost-update.exe', suspicious: true },
        { type: 'user', value: 'CORP\\jthompson', compromised: true },
      ],
      relationships: [
        { from: 'svchost-update.exe', to: 'updateservice-cdn.net', type: 'dns_query' },
        { from: '10.0.5.42', to: '185.220.101.34', type: 'network_connection' },
        { from: 'CORP\\jthompson', to: 'svchost-update.exe', type: 'process_owner' },
      ],
    },
    retry_count: 0,
    execution_context: 'local',
  },
  {
    id: 'step-005',
    name: 'guardrail_check',
    status: 'completed',
    started_at: offsetTime(6100),
    completed_at: offsetTime(6500),
    duration_ms: 400,
    guardrail_score: 87,
    guardrail_threshold: 50,
    input: {
      checks: [
        'code_safety_validation',
        'output_completeness',
        'evidence_quality',
        'ioc_coverage',
        'confidence_calibration',
      ],
    },
    output: {
      passed: true,
      code_safety: 'pass',
      output_completeness: 'pass',
      evidence_quality: 'high',
      ioc_coverage: '3/3 IOCs investigated',
      confidence_calibration: 'well-calibrated',
      score_breakdown: {
        code_safety: 20,
        output_completeness: 18,
        evidence_quality: 17,
        ioc_coverage: 16,
        confidence_calibration: 16,
      },
    },
    retry_count: 0,
    execution_context: 'local',
  },
  {
    id: 'step-006',
    name: 'generate_report',
    status: 'completed',
    started_at: offsetTime(6500),
    completed_at: offsetTime(8600),
    duration_ms: 2100,
    model_name: 'zovarc-standard',
    input: {
      report_type: 'incident',
      format: 'markdown',
      include_timeline: true,
      include_recommendations: true,
    },
    output: {
      severity: 'high',
      verdict: 'malicious',
      confidence: 0.94,
      title: 'Active C2 Beacon — updateservice-cdn.net',
      summary: 'Host 10.0.5.42 (user CORP\\jthompson) is beaconing to updateservice-cdn.net every ~30s via svchost-update.exe. Domain registered 3 days ago, resolves to known Tor exit node. 14/72 VT detections.',
      recommendations: [
        'Isolate host 10.0.5.42 from network immediately',
        'Block updateservice-cdn.net and 185.220.101.34 at perimeter firewall',
        'Reset credentials for CORP\\jthompson',
        'Forensic image of 10.0.5.42 for further analysis',
        'Hunt for svchost-update.exe across enterprise',
      ],
    },
    retry_count: 0,
    execution_context: 'llm',
  },
  {
    id: 'step-007',
    name: 'complete',
    status: 'completed',
    started_at: offsetTime(8600),
    completed_at: offsetTime(8700),
    duration_ms: 100,
    input: {
      finalize: true,
    },
    output: {
      total_duration_ms: 8700,
      entities_found: 5,
      playbook_triggered: 'isolate_and_block',
      playbook_actions: ['network_isolate', 'firewall_block', 'credential_reset'],
      investigation_status: 'complete',
    },
    retry_count: 0,
    execution_context: 'local',
  },
];

export const C2_BEACON_INVESTIGATION = {
  id: 'demo-c2-001',
  alert_type: 'C2 Beacon Communication',
  severity: 'high' as const,
  verdict: 'malicious' as const,
  confidence: 0.94,
  steps: C2_BEACON_STEPS,
  created_at: BASE_TIME,
  completed_at: offsetTime(8700),
  total_duration_ms: 8700,
  entity_count: 5,
  playbook: 'isolate_and_block',
};
