"""Delimiters for section-aware LLM context trimming (analyze ↔ llm_client)."""

CORRELATION_START = "<<<ZOVARK_CORRELATION_CONTEXT>>>"
CORRELATION_END = "<<</ZOVARK_CORRELATION_CONTEXT>>>"
INSTITUTIONAL_START = "<<<ZOVARK_INSTITUTIONAL_KNOWLEDGE>>>"
INSTITUTIONAL_END = "<<</ZOVARK_INSTITUTIONAL_KNOWLEDGE>>>"
